[cleaner]
    days_ago = 90

[reader]
    base_directory = "data"
    feeds = [
        "https://ecf.dcd.uscourts.gov/cgi-bin/rss_outside.pl",
        "https://ecf.nyed.uscourts.gov/cgi-bin/readyDockets.pl",
        ## "https://ecf.cacd.uscourts.gov/cgi-bin/rss_outside.pl",
        ## "https://ecf.nysd.uscourts.gov/cgi-bin/rss_outside.pl",
    ]

[filter]
    dockets = ["2:23-cv-04570-HG"]

[writer]
    format = "html"  # Or md or csv
    page_size = 20
    base_directory = "output"

[notifier.smtp]
    # Details found in ~/fdrdr_config.toml

[notifier.ses]
    admin = "admin@domain.smtp.your_host"
    send_to = "slott56@gmail.com"

[monitor]
    every = ["07:00", "20:00"]
