"""
Common test fixtures.
"""
import datetime
from pathlib import Path
from textwrap import dedent
from unittest.mock import Mock

import pytest
from pydantic.networks import AnyUrl

import model
import common


@pytest.fixture()
def xml_doc():
    return dedent(
        """\
        <!--  RSS generated by Eastern District of New York on Thu, 28 Dec 2023 21:20:01 GMT  -->
        <rss version="2.0">
        <channel>
        <title>Eastern District of New York Filings Entries on cases</title>
        <link>https://ecf.nyed.uscourts.gov</link>
        <description>Public Filings in the last 24 Hours</description>
        <lastBuildDate>Thu, 28 Dec 2023 21:20:01 GMT</lastBuildDate>
        <image>
        <title>Eastern District of New York</title>
        <url>http://www.nyed.uscourts.gov/Home_NBanner.GIF</url>
        <link>https://ecf.nyed.uscourts.gov</link>
        </image>
        <item>
        <title>
        <![CDATA[ 2:23-cv-09491-PKC-ST Sookra v. Berkeley Carroll School et al ]]>
        </title>
        <pubDate>Thu, 28 Dec 2023 21:18:55 GMT</pubDate>
        <author/>
        <guid isPermaLink="true">https://ecf.nyed.uscourts.gov/cgi-bin/DktRpt.pl?508001</guid>
        <description>
        <![CDATA[ [Quality Control Check - Summons] Sookra v. Berkeley Carroll School et al ]]>
        </description>
        <link>https://ecf.nyed.uscourts.gov/cgi-bin/DktRpt.pl?508001</link>
        </item>
        <item>
        <title>
        <![CDATA[ 2:23-cv-08293-NJC-ST Miller v. Sanofi US Services Inc. et al ]]>
        </title>
        <pubDate>Thu, 28 Dec 2023 21:18:41 GMT</pubDate>
        <author/>
        <guid isPermaLink="true">https://ecf.nyed.uscourts.gov/cgi-bin/DktRpt.pl?505703</guid>
        <description>
        <![CDATA[ [Order to Show Cause] Miller v. Sanofi US Services Inc. et al ]]>
        </description>
        <link>https://ecf.nyed.uscourts.gov/cgi-bin/DktRpt.pl?505703</link>
        </item>
        </channel>
        </rss>
        """
    )


@pytest.fixture
def mock_channel():
    c = model.Channel(
        title="Eastern District of New York Filings Entries on cases",
        link=AnyUrl("https://ecf.nyed.uscourts.gov/"),
        description="Public Filings in the last 24 Hours",
        last_build=datetime.datetime(2023, 12, 28, 21, 20, 1),
    )
    return c


@pytest.fixture
def mock_item():
    item = model.USCourtItem(
        title="2:23-cv-08293-NJC-ST Miller v. Sanofi US Services Inc. et al",
        link=AnyUrl("https://ecf.nyed.uscourts.gov/cgi-bin/DktRpt.pl?505703"),
        description="[Order to Show Cause] Miller v. Sanofi US Services Inc. et al",
        text_pub_date="Fri, 29 Dec 2023 21:23:33 GMT",
        docket="2:23-cv-08293-NJC-ST",
        parties="Miller v. Sanofi US Services Inc. et al",
    )
    return item


@pytest.fixture
def mock_item_detail(mock_channel, mock_item):
    return model.USCourtItemDetail(item=mock_item, channel=mock_channel)


@pytest.fixture()
def mock_no_config(tmp_path, monkeypatch):
    monkeypatch.setattr(
        common, "Path", Mock(wraps=Path, cwd=Mock(return_value=tmp_path))
    )
